# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Device Farmer
description: >-
  Device Farmer is a web application for debugging smartphones, smartwatches and other gadgets remotely, from the comfort of your browser.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devicefarmer.github.io" 
github_username: devicefarmer

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
